name: Create and publish the slurmctld container image

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - docker/slurmctld/**
  pull_request:
    branches:
      - main
    paths:
      - docker/slurmctld/**

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}/slurmctld

jobs:

  build-base-image:
    strategy:
      matrix:
        ubuntu-base-tag:
          - "22.04"
    uses: ${{ env.REGISTRY }}/ikim-essen/${{ github.repository }}/.github/workflows/slurm-base-image.yml@main
    with:
      ubuntu-base-tag: ${{ matrix.ubuntu-base-tag }}

  build-and-push-image:
    runs-on: ubuntu-latest
    needs: build-base-image
    strategy:
      fail-fast: true
      matrix:
        ubuntu_base_tag:
          - "22.04"
    
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Log into the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Retrieve base image build artifact
        uses: actions/download-artifact@v3
        with:
          name: baseimg-${{ matrix.ubuntu_base_tag }}
          path: /tmp
      
      - name: Load base image
        run: |
          docker load --input /tmp/baseimg-${{ matrix.ubuntu_base_tag }}.tar

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=branch
            type=ref,event=tag
            type=ref,event=pr
            # On the default branch, use a tag which reflects the base image
            type=raw,value=ubuntu-${{ matrix.ubuntu_base_tag }},enable={{is_default_branch}}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: docker/slurmctld
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            BASE_IMG="${{ env.REGISTRY }}/${{ github.repository }}/slurmbase:main"
