name: Rebuild slurm with nvml autodetect support

on:
  push:
    # The tag must match the Ubuntu version of the slurm package.
    tags:
      - "*.*.*-*"

defaults:
  run:
    shell: /usr/bin/bash -eo pipefail {0}

env:
  DEBIAN_FRONTEND: noninteractive

jobs:
  build-debs-and-release:
    strategy:
      matrix:
        runner_version: ["22.04", "24.04"]
    runs-on: ubuntu-${{ matrix.runner_version }}
    permissions:
      contents: write
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Prepare the environment
        run: |
          SLURM_VERSION="${{ github.ref_name }}"
          echo "SLURM_VERSION=${SLURM_VERSION}" >> "${GITHUB_ENV}"
          UBUNTU_VERSION="${{ matrix.runner_version }}"
          echo "UBUNTU_VERSION=${UBUNTU_VERSION}" >> "${GITHUB_ENV}"

          # Pick the correct source package based on the version being built.
          SLURM_SRC_PKG="slurm-wlm"
          case "${SLURM_VERSION}" in
            21.08.* )
              DEB_SOURCE_REPO="jammy universe"
              ;;
            23.02.* )
              DEB_SOURCE_REPO="mantic universe"
              ;;
            23.11.* )
              DEB_SOURCE_REPO="noble universe"
              ;;
            24.05.* )
              DEB_SOURCE_REPO="oracular universe"
              ;;
            * )
              1>&2 echo "No deb source repo for Slurm version ${SLURM_VERSION}"
              false
              ;;
          esac
          echo "SLURM_SRC_PKG=${SLURM_SRC_PKG}" >> "${GITHUB_ENV}"
          echo "DEB_SOURCE_REPO=${DEB_SOURCE_REPO}" >> "${GITHUB_ENV}"

          # Patch the build files to build separate slurm-wlm-nvml-plugin
          # package and be able to build on newer and/or older OS versions.
          # These use sed etc. instead of actual .patch files since otherwise
          # we'd need to maintain version-specific .patch files.
          PATCHES_SH="$(pwd)/patches.sh"
          >> "${PATCHES_SH}" echo '#! /bin/sh -xeu'
          chmod +x -- "${PATCHES_SH}"
          >> "${PATCHES_SH}" cat \
            ./patches/add-slurm-wlm-nvml-plugin.sh \
            ./patches/libslurm-slurm_strlcpy-only-ifndef-HAVE_STRLCPY.sh \
            ./patches/drop-dpkg-dev-debhelper-min-version-constraints.sh
          [ "${UBUNTU_VERSION%%.*}" -lt 23 ] &&
            >> "${PATCHES_SH}" cat \
              ./patches/remove-slurm-wlm-rsmi-plugin.sh
          [ "${UBUNTU_VERSION%%.*}" -lt 21 ] &&
            >> "${PATCHES_SH}" cat \
              ./patches/revert-to-pmix-3-prefix.sh
          echo "PATCHES_SH=${PATCHES_SH}" >> "${GITHUB_ENV}"

          BUILDDIR="${SLURM_SRC_PKG}-${SLURM_VERSION}-ubuntu${UBUNTU_VERSION}-debs"
          echo "BUILDDIR=${BUILDDIR}" >> "${GITHUB_ENV}"

      - name: Enable the source repository
        run: |
          echo "deb-src http://archive.ubuntu.com/ubuntu/ ${DEB_SOURCE_REPO}" |
            sudo tee -a /etc/apt/sources.list.d/debsrc.list
          # Use old-releases.ubuntu.com for non-LTS EOL versions.
          for f in /etc/apt/sources.list /etc/apt/sources.list.d/*; do
            sed -Ei \
              '/ubuntu\.com\/ubuntu\/ (kinetic|lunar|mantic)/ {
                s|http://[^.]*|http://old-releases|
              }' \
              -- "${f}"
          done
          sudo apt-get update

      - name: Install the Ubuntu build tools
        run: |
          sudo apt-get -y install --no-install-recommends \
            devscripts equivs

      - name: Install the NVIDIA build dependencies
        run: |
          sudo apt-get -y install libnvidia-ml-dev

      - name: Prepare the build directory
        run: mkdir "${BUILDDIR}"

      - name: Download the build sources
        working-directory: ${{ env.BUILDDIR }}
        run: |
          sudo apt-get source --only-source "${SLURM_SRC_PKG}=${SLURM_VERSION}"
          cd "${SLURM_SRC_PKG}-"*
          "${PATCHES_SH}"

      - name: Install the build dependencies
        working-directory: ${{ env.BUILDDIR }}
        run: |
          cd "${SLURM_SRC_PKG}-"*
          mk-build-deps \
            -t 'apt-get -o Debug::pkgProblemResolver=yes --no-install-recommends -y' \
            -i debian/control

      - name: Build the package
        working-directory: ${{ env.BUILDDIR }}
        run: |
          cd "${SLURM_SRC_PKG}-"*
          debuild -us -uc -b

      - name: Verify that the nvml library was built
        working-directory: ${{ env.BUILDDIR }}
        run: dpkg-deb -c slurm-wlm-nvml-plugin_*_amd64.deb | grep -q gpu_nvml.so

      - name: Create the release archive
        run: |
          tar --verbose --create --auto-compress \
            --file "${BUILDDIR}.tar.gz" \
            "${BUILDDIR}"/*.deb \
            "${BUILDDIR}"/*.buildinfo \
            "${BUILDDIR}"/*.changes \
            "${BUILDDIR}"/*.build

      - name: Create the release
        uses: softprops/action-gh-release@v1
        with:
          body: |
            # Slurm ${{ env.SLURM_VERSION }} with gpu/nvml
          files: ${{ env.BUILDDIR }}.tar.gz
          fail_on_unmatched_files: true
