name: Create and publish the slurm container images

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - docker/slurmctld/**
      - docker/slurmdbd/**
  pull_request:
    branches:
      - main
    paths:
      - docker/slurmctld/**
      - docker/slurmdbd/**

env:
  REGISTRY: ghcr.io
  BASE_IMG: ${{ github.repository }}/slurmbase

jobs:

  build-and-push-slurm-components:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        ubuntu_base_tag:
          - "22.04"
        slurm_component:
          - "slurmctld"
          - "slurmdbd"
    
    env:
      IMAGE_NAME: ${{ github.repository }}/${{ matrix.slurm_component }}

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Log into the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            # On the default branch, use a tag which reflects the base image
            type=raw,value=ubuntu-${{ matrix.ubuntu_base_tag }},enable={{is_default_branch}}
            # On other branches, add the base image name to the tag as a suffix
            type=ref,event=branch,suffix=-ubuntu-${{ matrix.ubuntu_base_tag }}
            type=ref,event=tag,suffix=-ubuntu-${{ matrix.ubuntu_base_tag }}
            type=ref,event=pr,suffix=-ubuntu-${{ matrix.ubuntu_base_tag }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: docker/${{ matrix.slurm_component }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            BASE_IMG=${{ env.BASE_IMG }}
