name: Rebuild slurm with nvml autodetect support

on:
  workflow_dispatch:
  push:
    tags:
      - "v*.*.*"

defaults:
  run:
    shell: /usr/bin/bash -eo pipefail {0}

jobs:
  build-debs-and-release:
    strategy:
      matrix:
        runner_version: ["22.04"]
    runs-on: ubuntu-${{ matrix.runner_version }}
    permissions:
      contents: write
    env:
      NVIDIA_DRIVER_VERSION: "520"
      NVIDIA_CUDA_VERSION: "12-1"
      DEB_SOURCE_REPO: jammy
    steps:
      - name: Prepare the environment
        run: |
          SLURM_VERSION="$(echo "${{ github.ref_name }}" | sed 's/^v//')"
          BUILDDIR="slurm-${SLURM_VERSION}-ubuntu${{ matrix.runner_version }}-debs"
          echo "SLURM_VERSION=${SLURM_VERSION}" >> "${GITHUB_ENV}"
          echo "BUILDDIR=${BUILDDIR}" >> "${GITHUB_ENV}"
          echo "DEBIAN_FRONTEND=noninteractive" >> "${GITHUB_ENV}"
          mkdir "${BUILDDIR}"

      - name: Add the NVIDIA repository
        env:
          CUDA_KEYRING_VERSION: "1.1-1"
        run: |
          sudo apt-get update
          sudo apt-get -y install ca-certificates curl
          source /etc/os-release
          curl -LO "https://developer.download.nvidia.com/compute/cuda/repos/${ID}$(echo ${VERSION_ID} | tr -d ".")/x86_64/cuda-keyring_${CUDA_KEYRING_VERSION}_all.deb"
          sudo dpkg -i "cuda-keyring_${CUDA_KEYRING_VERSION}_all.deb"
          sudo ln -s "/usr/local/cuda-$(echo "${NVIDIA_CUDA_VERSION}" | tr "-" "." )" /usr/local/cuda

      - name: Add the ubuntu source repository
        run: |
          echo "deb-src http://archive.ubuntu.com/ubuntu ${DEB_SOURCE_REPO} universe main multiverse restricted"          | sudo tee -a /etc/apt/sources.list.d/debsrc.list
          echo "deb-src http://archive.ubuntu.com/ubuntu ${DEB_SOURCE_REPO}-updates universe main multiverse restricted"  | sudo tee -a /etc/apt/sources.list.d/debsrc.list
          echo "deb-src http://archive.ubuntu.com/ubuntu ${DEB_SOURCE_REPO}-security universe main multiverse restricted" | sudo tee -a /etc/apt/sources.list.d/debsrc.list

      - name: Install the build dependencies
        run: |
          sudo apt-get update
          sudo apt-get -y install \
            "libnvidia-compute-${NVIDIA_DRIVER_VERSION}" \
            "cuda-nvml-dev-${NVIDIA_CUDA_VERSION}"
          sudo apt-get build-dep "slurm-wlm=${SLURM_VERSION}"

      - name: Build the package
        working-directory: ${{ env.BUILDDIR }}
        run: sudo apt-get source --compile "slurm-wlm=${SLURM_VERSION}" | tee slurm-wlm.buildlog

      - name: Verify that the nvml library was built
        working-directory: ${{ env.BUILDDIR }}
        run: dpkg-deb -c slurm-wlm-basic-plugins_*_amd64.deb | grep gpu_nvml.so > /dev/null

      - name: Create the release archive
        run: |
          sudo apt-get -y install zip
          zip -r "${BUILDDIR}.zip" \
            "${BUILDDIR}"/*.deb \
            "${BUILDDIR}"/*.buildlog

      - name: Create the release
        uses: softprops/action-gh-release@v1
        with:
          body: |
            # Slurm ${{ github.ref_name }} with gpu/nvml

            Built with the following NVIDIA dependencies:

            - libnvidia-compute-${{ env.NVIDIA_DRIVER_VERSION }}
            - cuda-nvml-dev-${{ env.NVIDIA_CUDA_VERSION }}
          files: ${{ env.BUILDDIR }}.zip
          fail_on_unmatched_files: true
